### ISSUE TITLE
storage volume

### ISSUE THREAD

**Issue by publicocean0** [autopilotpattern/consul#53]
how to mount a volume where consul save KV store?

**Comment by tjcelaya** [comment]
The Consul documentation has a section on [persisting the data directory](https://www.consul.io/docs/guides/consul-containers.html#data-directory-persistence) which recommends mounting a [docker volume](https://docs.docker.com/compose/compose-file/compose-file-v2/#volume-configuration-reference) at `/consul/data` (or wherever you set [`-data-dir`](https://www.consul.io/docs/guides/consul-containers.html#data-directory-persistence)), e.g.

```yaml
version: '2'
services:
  consul:
    image: autopilotpattern/consul:1.0.0r43
    ...
    volumes:
     - consul_data:/consul/data
volumes:
  consul_data:
```

(it's fine for the `consul_data` key to be empty)

Note that when deployed on Triton these disks will persist across reboots as mentioned [in the README](https://github.com/autopilotpattern/consul#triton-specific-availability-advantages).
